---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: local.blueprint.com www.local.blueprint.com 10.10.10.14
    timezone: Pacific/Auckland
  vars_files:
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - composer
    - phpcommon
    - app
